spring:
  application:
    name: security-core

auth:
  mode: ${AUTH_MODE}
  jwt:
    secret-key: ${AUTH_JWT_SECRET-KEY}
    grant-type: ${AUTH_JWT_GRANT-TYPE}
  allowed-statuses: ${AUTH_ALLOWED-STATUSES}
  excluded-patterns: ${AUTH_EXCLUDED-PATTERNS}
